### ISSUE TITLE
Enable auto-update by default

### ISSUE THREAD

**Issue by trippyone** [Lacyway/SIT-Unofficial-Launcher#8]
We should enable auto-update by default (for the launcher). Once there is an update available, we should ask the user if they want to update and provide three options:

An update for SIT Launcher is available. Would you like to update now ?
- Yes
- No
- Don't ask again

**Comment by Lacyway** [comment]
This will be enabled after the next release. It won't ask the user, they have to disable it themselves if it really bothers them.
