### ISSUE TITLE
SIT bleeding edge support

### ISSUE THREAD

**Issue by trippyone** [Lacyway/SIT-Unofficial-Launcher#9]
Grab Github build actions (https://github.com/paulov-t/SIT.Core/actions/workflows/build-workflow.yml) and list them in the launcher as "Bleeding Edge" branch.

**Comment by Lacyway** [comment]
Use: https://api.github.com/repos/paulov-t/SIT.Core/actions/runs
With: https://api.github.com/repos/paulov-t/SIT.Core/actions/runs/6629760201 (id is based on first action what has "successful" as status)
Lastly: https://api.github.com/repos/paulov-t/SIT.Core/actions/runs/6629760201/artifacts (get the artifacts url from id above, might be able to skip "With:" stage)

From Lastly: Get `archive_download_url` where name is `SIT-Build-Release`

**Comment by Lacyway** [comment]
This needs an API token, unfortunately. `archive_download_url` requires a token to be downloaded.

**Comment by trippyone** [comment]
paulov don't like the idea of us polling pre-releases due to different reasons but one of them being that people are too dumb and will complain about bugs on SPT.
